dist: trusty
sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker
  - mongodb

env:
  - NODE_ENV=qa

cache: yarn

install:
  - yarn install
  - npm test
  - docker build -t $DOCKER_USERNAME/nestjs-seed .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/nestjs-seed
