version: "3"
services:
  mongo:
    image: mongo:3.4-jessie
    ports:
      - 3001:27017
    tmpfs: /data/db
  consul:
    image: consul
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    tmpfs: /consul/data
  app-test:
    build: .
    image: app
    command: npm run test
    depends_on:
      - mongo
      - consul
