apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: apijob
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apijob
        tier: frontend
    spec:
      containers:
      - image: tilen/demo-svc-job
        name: apijob
        ports:
        - containerPort: 3000
          name: server
          protocol: TCP
        env:
          - name: MONGO
            value: "ds129166.mlab.com:29166"
          - name: NODE_ENV
            value: "prod"
          - name: LOGSTASH_HOST
            value: "log.tomakic.com"
